[package]
name = "wictk"
version = "0.1.0"
edition = "2021"
homepage = "https://github.com/Frixxie/wictk"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = { version = "0.6.20", features = ["json"] }
hyper = { version = "0.14.27", features = ["full"] }
reqwest = { version = "0.11.20", features = ["json", "tokio-rustls"] }
serde = { version = "1.0.188", features = ["derive"] }
serde_json = "1.0.106"
tokio = { version = "1.32.0", features = ["full"] }
tower = "0.4.13"

[dev-dependencies]
pretty_assertions = "1.4.0"
http = "0.2.9"
