[package]
name = "wictk"
version = "0.1.15"
edition = "2021"
homepage = "https://github.com/Frixxie/wictk"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.81"
axum = { version = "0.7.4", features = ["json"] }
chrono = { version = "0.4.38", features = ["serde"] }
log = "0.4.21"
reqwest = { version = "0.12.0", features = ["json"] }
serde = { version = "1.0.197", features = ["derive"] }
serde_json = "1.0.114"
simple_logger = "4.3.3"
tokio = { version = "1.36.0", features = ["full"] }

[dev-dependencies]
pretty_assertions = "1.4.0"
