FROM rust:latest as build-stage
WORKDIR /usr/src/app
COPY . .
RUN cargo install --path client_logger

FROM rust:slim
COPY --from=build-stage /usr/local/cargo/bin/client_logger /usr/local/bin/client_logger
CMD ["client_logger"]
