FROM rust:latest as build-stage
WORKDIR /usr/src/app
COPY . .
RUN cargo install --path notifier

FROM rust:slim
COPY --from=build-stage /usr/local/cargo/bin/notifier /usr/local/bin/notifier
CMD ["notifier"]
