apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: wictk
    kustomize.toolkit.fluxcd.io/name: wictk-release
    kustomize.toolkit.fluxcd.io/namespace: flux-system
  name: wictk-ext
  namespace: default
spec:
  ports:
  - port: 3010
    protocol: TCP
    targetPort: 3000
  selector:
    io.kompose.service: wictk
  type: LoadBalancer
status:
  loadBalancer: {}
