name: Make-tagged

on:
  push:
    tags: [ '*.*.*' ]

env:
  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
  DOCKERTAG: ${{github.ref_name}}
  OPENWEATHERMAPAPIKEY: ${{ secrets.OPENWEATHERMAPAPIKEY }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: make build
        run: make build
      - name: make test
        run: make test
      - name: make container_tagged
        run: make container_tagged

  generate-changelog:
    name: Generate changelog
    runs-on: ubuntu-22.04
    outputs:
      release_body: ${{ steps.git-cliff.outputs.content }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Generate a changelog
        uses: orhun/git-cliff-action@main
        id: git-cliff
        with:
          config: cliff.toml
          args: -vv --latest --no-exec --github-repo ${{ github.repository }}
        env:
          OUTPUT: CHANGES.md
